create table CARS
(    ID NUMBER(5)
   , NAME VARCHAR2(50)
   , LUXERYBRAND VARCHAR2(1)
   , CONSTRAINT CAR_PK PRIMARY KEY (ID)
);

create or replace public synonym CARS for CARS;

create table MODELS
(
     ID NUMBER(5)
   , DESCRIPTION VARCHAR2(100)
   , CAR_ID NUMBER(5)
   , CONSTRAINT MODEL_PK PRIMARY KEY (ID)

);

create table MODELVERSIONS
(
    ID NUMBER(5)
  , MODEL_ID NUMBER(5)
  , DESCRIPTION VARCHAR2(100)
  , STARTDATE DATE
  , ENDDATE DATE
);

create or replace public synonym MODELS for MODELS;

ALTER TABLE MODELS ADD CONSTRAINT MODEL_CAR_FK FOREIGN KEY (CAR_ID) REFERENCES CARS (ID);
ALTER TABLE MODELVERSIONS ADD CONSTRAINT MODELVERSION_MODEL_FK FOREIGN KEY (MODEL_ID) REFERENCES MODELS (ID);

INSERT INTO CARS VALUES (1, 'BMW', 'J');
INSERT INTO CARS VALUES (2, 'FORD', 'N');

INSERT INTO MODELS VALUES (1,'1-series',1);
INSERT INTO MODELS VALUES (2,'Escort',2);
INSERT INTO MODELS VALUES (3,'Focus',2);

INSERT INTO MODELVERSIONS VALUES (1,1,'2015 version',to_date('01-01-2015','dd-mm-yyyy'), to_date('31-12-2015','dd-mm-yyyy'));
INSERT INTO MODELVERSIONS VALUES (2,1,'2016 version',to_date('01-01-2016','dd-mm-yyyy'), to_date('31-12-2016','dd-mm-yyyy'));
INSERT INTO MODELVERSIONS VALUES (3,1,'2017 version',to_date('01-01-2017','dd-mm-yyyy'), null);
INSERT INTO MODELVERSIONS VALUES (4,2,'Version A',to_date('01-01-2016','dd-mm-yyyy'), to_date('31-12-2016','dd-mm-yyyy'));
INSERT INTO MODELVERSIONS VALUES (5,3,'Version B',to_date('01-01-2017','dd-mm-yyyy'), null);
COMMIT;

/*
DROP TABLE MODELVERSIONS PURGE;
DROP TABLE MODELS PURGE;
DROP TABLE CARS PURGE;

drop public synonym MODELS;
drop public synonym CARS;
*/